//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Pantheon
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using WPILib.Extras;

	public class TankDrive : IDrive
	{

        public TankDrive(XboxController nxbox, IMotor nmotor) : base(nxbox, nmotor)
        {

        }

        private void GetInput()
		{
			throw new System.NotImplementedException();
		}

	}
}

