//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pantheon.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IReporter")]
    public interface IReporter {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporter/ReportData", ReplyAction="http://tempuri.org/IReporter/ReportDataResponse")]
        void ReportData(string key, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporter/ReportData", ReplyAction="http://tempuri.org/IReporter/ReportDataResponse")]
        System.Threading.Tasks.Task ReportDataAsync(string key, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporter/GetData", ReplyAction="http://tempuri.org/IReporter/GetDataResponse")]
        string GetData(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporter/GetData", ReplyAction="http://tempuri.org/IReporter/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporter/GetAllData", ReplyAction="http://tempuri.org/IReporter/GetAllDataResponse")]
        System.Collections.Generic.Dictionary<string, string> GetAllData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReporter/GetAllData", ReplyAction="http://tempuri.org/IReporter/GetAllDataResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetAllDataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReporterChannel : ServiceReference1.IReporter, System.ServiceModel.IClientChannel {
    }
    


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReporterClient : System.ServiceModel.ClientBase<IReporter>, ServiceReference1.IReporter {
        
        public ReporterClient() {
        }
        
        public ReporterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReporterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ReportData(string key, string value) {
            base.Channel.ReportData(key, value);
        }
        
        public System.Threading.Tasks.Task ReportDataAsync(string key, string value) {
            return base.Channel.ReportDataAsync(key, value);
        }
        
        public string GetData(string key) {
            return base.Channel.GetData(key);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(string key) {
            return base.Channel.GetDataAsync(key);
        }
        
        public System.Collections.Generic.Dictionary<string, string> GetAllData() {
            return base.Channel.GetAllData();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetAllDataAsync() {
            return base.Channel.GetAllDataAsync();
        }
    }
}
