//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Pantheon
{
    /// <summary>
    /// Template class for all robot Control objects that are contained in 
    /// </summary>
    public abstract class IControl
    {
        /// <summary>
        /// Method to run during the Telerop Initialization phase of the match.
        /// </summary>
        public virtual void TeleopInit() { }

        /// <summary>
        /// Called every cycle during the teleoperated periodic phase.
        /// </summary>
        public virtual void TeleopPeriodic() { }

        /// <summary>
        /// Method to run during the Autonomous Initilization phase of the match.
        /// </summary>
        public virtual void AutoInit() { }

        /// <summary>
        /// Called every cycle during the Autonomous periodic phase.
        /// </summary>
        public virtual void AutoPeriodic() { }

        /// <summary>
        /// Called at the end of every phase.
        /// </summary>
        public virtual void DisabledInit() { }

        /// <summary>
        /// Called every cycle the robot is diabled.
        /// </summary>
        public virtual void DisabledPeriodic() { }
    }
}

