//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using WPILib.SmartDashboard;
using Pantheon.ServiceReference1;

namespace Pantheon
{
    public class SmartWriter
    {
        private static ReporterClient _reporterInstance;

        public static ReporterClient ReporterInstance
        {
            get
            {
                if (_reporterInstance == null)
                    _reporterInstance = new ReporterClient();

                return _reporterInstance;
            }
        }

        public static void WriteString(string label, string value, DebugMode Debug)
        {
            if (Global.DMode >= Debug)
            {
                SmartDashboard.PutString(label, value);
                if (Global.DisplayConsoleOutput) Console.WriteLine(label + " : " + value);
            }

            ReporterInstance.ReportData(label, value);
        }

        public static void WriteBool(string label, bool value, DebugMode Debug)
        {
            if (Global.DMode >= Debug)
            {
                SmartDashboard.PutBoolean(label, value);
                if (Global.DisplayConsoleOutput) Console.WriteLine(label + " : " + value);
            }
            ReporterInstance.ReportData(label, value.ToString());
        }

        public static void WriteNumber(string label, double value, DebugMode Debug)
        {
            if (Global.DMode >= Debug)
            {
                SmartDashboard.PutNumber(label, value);
                if (Global.DisplayConsoleOutput) Console.WriteLine(label + " : " + value);
            }
            ReporterInstance.ReportData(label, value.ToString());
        }

    }
}

