//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Pantheon
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using WPILib;


    public class JaguarMotor : InteruptableMotor
	{
		private Jaguar BackLeft
		{
			get;
			set;
		}

		private Jaguar BackRight
		{
			get;
			set;
		}

		private Jaguar FrontRight
		{
			get;
			set;
		}

		private Jaguar FrontLeft
		{
			get;
			set;
		}

		public override void AutoInit()
		{
			throw new System.NotImplementedException();
		}

		public override void AutoPeriodic()
		{
			throw new System.NotImplementedException();
		}

		public override void DisabledInit()
		{
			throw new System.NotImplementedException();
		}

		public override void Set(double left, double right)
		{
			throw new System.NotImplementedException();
		}

		public override void Stop()
		{
			throw new System.NotImplementedException();
		}

		public override void TeleopInit()
		{
			throw new System.NotImplementedException();
		}

		public override void TeleopPeriodic()
		{
			throw new System.NotImplementedException();
		}

		public override void RobotInit()
		{
			throw new System.NotImplementedException();
		}

	}
}

