//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Pantheon
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class SmartWriter
	{


		public static void WriteString(string label, string value, DebugMode Debug)
		{
			throw new System.NotImplementedException();
		}

		public virtual void Operation1()
		{
			throw new System.NotImplementedException();
		}

		public static void WriteBool(string label, bool value, DebugMode Debug)
		{
			throw new System.NotImplementedException();
		}

		public static void WriteNumber(string label, double value, DebugMode Debug)
		{
			throw new System.NotImplementedException();
		}

	}
}

