//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Pantheon
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

    /// <summary>
    /// I can even define my own documentation that will show up in the object browser
    /// </summary>
	public class IControl
	{
		public virtual void TeleopInit()
		{
			 
		}

		public virtual void TeleopPeriodic()
		{
			 
		}

		public virtual void AutoInit()
		{
			 
		}

		public virtual void AutoPeriodic()
		{
			 
		}

		public virtual void DisabledInit()
		{
			 
		}

        public virtual void DisabledPeriodic()
        {
 
        }


        public virtual void RobotInit()
		{
		}

	}
}

