//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Pantheon
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using WPILib;
    using WPILib.Extras;

    /// <summary>
    /// Arcade Style Drive Train Style that is feed a <typeparamref IMotor="IMotor"/>  to control
    /// </summary>
	public class ArcadeDrive : IDrive
	{
        
        /// <summary>
        /// Create a new arcade drive system using an XboxController, and a IMotor
        /// all functions only activate during teleoperated
        /// </summary>
        /// <param name="nxbox"> XboxController </param>
        /// <param name="nmotor"> IMotor </param>
        public ArcadeDrive(XboxController nxbox, IMotor nmotor) : base(nxbox, nmotor)
        { }
        

		private void GetInput()
		{
            double x = xbox.GetLeftXAxis();
            double y = xbox.GetLeftYAxis();

            y += .5;
            x *= .8;

            double left;
            double right;

            left = y;
            right = y;

            left -= x;
            right -= x;

            motor.Set(right, left);
		}

        public override void TeleopPeriodic()
        {
            GetInput();
        }

        }
    }



