//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Pantheon
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class IMotor : IControl
	{
        protected double SetValue;
        protected MotorMode mMode = MotorMode.Stopped;

        public abstract bool Inverted { get; set; }

        protected abstract void Apply();
                

        public void Set(double set)
        {
            SetValue = set;
        }

        public override void AutoInit()
        {
            Set(0.0f);
            Apply();
            mMode = MotorMode.UserControl;
        }

        public override void AutoPeriodic()
        {
            Apply();
        }

        public override void TeleopInit()
        {
            Set(0.0f);
            Apply();
            mMode = MotorMode.UserControl;
        }

        public override void TeleopPeriodic()
        {
            Apply();
        }

        public override void DisabledInit()
        {
            Apply();
            mMode = MotorMode.Stopped;
        }
    }
}

