//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Pantheon
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using WPILib;
    

	public class InteruptableMotor : IMotor
	{
		protected virtual double RightSet
		{
			get;
			set;
		}

		protected virtual double LeftSet
		{
			get;
			set;
		}

        public double LeftExterior
        {
            get;
            set;
        }

        public double RightExterior
        {
            get;
            set;
        }

		public virtual MotorMode mode
		{
			get;
			set;
		}

		protected virtual void Update()
		{
            switch (mode)
            {
                case MotorMode.Auto:
                    LeftSet = LeftExterior;
                    RightSet = RightExterior;
                    break;
                case MotorMode.Stopped:
                    LeftSet = 0;
                    RightSet = 0;
                    break;
            }
		}

	}
}

