//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pantheon
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using WPILib;


    public class TalonMotor : IMotor
	{
        private Talon motor;
        public override bool Inverted
        {
            get
            {
                return motor.Inverted;
            }

            set
            {
                motor.Inverted = value;
            }
        }

        public TalonMotor(int port)
        {
            motor = new Talon(port);
        }

        protected override void Apply()
        {
            motor.Set(SetValue);
        }
    }
}

