//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pantheon.Services {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.IReportingService")]
    public interface IReportingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportingService/GetData", ReplyAction="http://tempuri.org/IReportingService/GetDataResponse")]
        string GetData(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportingService/GetData", ReplyAction="http://tempuri.org/IReportingService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportingService/ReportData", ReplyAction="http://tempuri.org/IReportingService/ReportDataResponse")]
        void ReportData(string key, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportingService/ReportData", ReplyAction="http://tempuri.org/IReportingService/ReportDataResponse")]
        System.Threading.Tasks.Task ReportDataAsync(string key, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportingService/GetAllData", ReplyAction="http://tempuri.org/IReportingService/GetAllDataResponse")]
        System.Collections.Generic.Dictionary<string, string> GetAllData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportingService/GetAllData", ReplyAction="http://tempuri.org/IReportingService/GetAllDataResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetAllDataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportingServiceChannel : IReportingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportingServiceClient : System.ServiceModel.ClientBase<IReportingService>, IReportingService {
        
        public ReportingServiceClient() {
        }
        
        public ReportingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(string key) {
            return base.Channel.GetData(key);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(string key) {
            return base.Channel.GetDataAsync(key);
        }
        
        public void ReportData(string key, string value) {
            base.Channel.ReportData(key, value);
        }
        
        public System.Threading.Tasks.Task ReportDataAsync(string key, string value) {
            return base.Channel.ReportDataAsync(key, value);
        }
        
        public System.Collections.Generic.Dictionary<string, string> GetAllData() {
            return base.Channel.GetAllData();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetAllDataAsync() {
            return base.Channel.GetAllDataAsync();
        }
    }
}
