//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Pantheon
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class IControl
	{
		public virtual void TeleopInit()
		{
			throw new System.NotImplementedException();
		}

		public virtual void TeleopPeriodic()
		{
			throw new System.NotImplementedException();
		}

		public virtual void AutoInit()
		{
			throw new System.NotImplementedException();
		}

		public virtual void AutoPeriodic()
		{
			throw new System.NotImplementedException();
		}

		public virtual void DisabledInit()
		{
			throw new System.NotImplementedException();
		}

		public virtual void RobotInit()
		{
			throw new System.NotImplementedException();
		}

	}
}

