//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Pantheon
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class IMotor : IControl
	{
		private int FrontLeft
		{
			get;
			set;
		}

		private int FrontRight
		{
			get;
			set;
		}

		private int BackLeft
		{
			get;
			set;
		}

		private int BackRight
		{
			get;
			set;
		}

		public virtual void Set(double right, double left)
		{
			throw new System.NotImplementedException();
		}

		public virtual void Stop()
		{
			throw new System.NotImplementedException();
		}

	}
}

