//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Pantheon
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Jaguar : InteruptableMotor
	{
		private Jaguar BackLeft
		{
			get;
			set;
		}

		private Jaguar BackRight
		{
			get;
			set;
		}

		private Jaguar FrontRight
		{
			get;
			set;
		}

		private Jaguar FrontLeft
		{
			get;
			set;
		}

		public virtual void AutoInit()
		{
			throw new System.NotImplementedException();
		}

		public virtual void AutoPeriodic()
		{
			throw new System.NotImplementedException();
		}

		public virtual void DisabledInit()
		{
			throw new System.NotImplementedException();
		}

		public virtual void Set(double left, double right)
		{
			throw new System.NotImplementedException();
		}

		public virtual void Stop()
		{
			throw new System.NotImplementedException();
		}

		public virtual void TeleopInit()
		{
			throw new System.NotImplementedException();
		}

		public virtual void TeleopPeriodic()
		{
			throw new System.NotImplementedException();
		}

		public virtual void RobotInit()
		{
			throw new System.NotImplementedException();
		}

	}
}

